perform environment calculation in Python
Signed-off-by: Dirk Thomas <dirk-thomas@users.noreply.github.com>

diff --git a/ament_package/template/prefix_level/local_setup.sh.in b/ament_package/template/prefix_level/local_setup.sh.in
--- a/ament_package/template/prefix_level/local_setup.sh.in
+++ b/ament_package/template/prefix_level/local_setup.sh.in
@@ -1,8 +1,18 @@
 # generated from ament_package/template/prefix_level/local_setup.sh.in
 
-# since this file is sourced use either the provided AMENT_CURRENT_PREFIX
-# or fall back to the destination set at configure time
-: ${AMENT_CURRENT_PREFIX:=@CMAKE_INSTALL_PREFIX@}
+# since a plain shell script can't determine its own path when being sourced
+# either use the provided AMENT_CURRENT_PREFIX
+# or fall back to the build time prefix (if it exists)
+_ament_prefix_sh_AMENT_CURRENT_PREFIX="@CMAKE_INSTALL_PREFIX@"
+if [ -z "$AMENT_CURRENT_PREFIX" ]; then
+  if [ ! -d "$_ament_prefix_sh_AMENT_CURRENT_PREFIX" ]; then
+    echo "The build time path \"$_ament_prefix_sh_AMENT_CURRENT_PREFIX\" doesn't exist. Either source a script for a different shell or set the environment variable \"AMENT_CURRENT_PREFIX\" explicitly." 1>&2
+    unset _ament_prefix_sh_AMENT_CURRENT_PREFIX
+    return 1
+  fi
+else
+  _ament_prefix_sh_AMENT_CURRENT_PREFIX="$AMENT_CURRENT_PREFIX"
+fi
 
 # set type of shell if not already set
 : ${AMENT_SHELL:=sh}
@@ -24,38 +34,36 @@ if [ ! -f "$_ament_python_executable" ]; then
   fi
 fi
 
-# get all packages in topological order
-_ORDERED_PACKAGES="$($_ament_python_executable "$AMENT_CURRENT_PREFIX/_order_packages.py" "$AMENT_CURRENT_PREFIX")"
-unset _ament_python_executable
+# function to source another script with conditional trace output
+# first argument: the path of the script
+_ament_prefix_sh_source_script() {
+  if [ -f "$1" ]; then
+    if [ -n "$AMENT_TRACE_SETUP_FILES" ]; then
+      echo ". \"$1\""
+    fi
+    . "$1"
+  else
+    echo "not found: \"$1\"" 1>&2
+  fi
+}
 
-# source prefix-level local_setup.EXT or local_setup.sh file for each package
-_prefix_local_setup_IFS=$IFS
-IFS="
-"
-# store AMENT_CURRENT_PREFIX to restore it before each package
-_prefix_local_setup_AMENT_CURRENT_PREFIX=$AMENT_CURRENT_PREFIX
-if [ "$AMENT_SHELL" = "zsh" ]; then
-  ament_zsh_to_array _ORDERED_PACKAGES
+# get all commands in topological order
+_ament_additional_extension=""
+if [ "$AMENT_SHELL" != "sh" ]; then
+  _ament_additional_extension="${AMENT_SHELL}"
 fi
-for _package in $_ORDERED_PACKAGES; do
-  # restore AMENT_CURRENT_PREFIX for each prefix-level local_setup file
-  AMENT_CURRENT_PREFIX="$_prefix_local_setup_AMENT_CURRENT_PREFIX"
-  # restore IFS before sourcing other files
-  IFS=$_prefix_local_setup_IFS
-  _path="$AMENT_CURRENT_PREFIX/share/$_package/local_setup.$AMENT_SHELL"
-  # trace output
-  if [ -n "$AMENT_TRACE_SETUP_FILES" ]; then
-    echo ". \"$_path\""
-  fi
-  if [ -f "$_path" ]; then
-    . "$_path"
-  fi
-  unset _path
-done
-unset _package
-unset _ORDERED_PACKAGES
+_ament_ordered_commands="$($_ament_python_executable "$_ament_prefix_sh_AMENT_CURRENT_PREFIX/_local_setup_util.py" sh $_ament_additional_extension)"
+unset _ament_additional_extension
+unset _ament_python_executable
+if [ -n "$AMENT_TRACE_SETUP_FILES" ]; then
+  echo "Execute generated script:"
+  echo "<<<"
+  echo "${_ament_ordered_commands}"
+  echo ">>>"
+fi
+eval "${_ament_ordered_commands}"
+unset _ament_ordered_commands
 
-unset _prefix_local_setup_AMENT_CURRENT_PREFIX
-IFS=$_prefix_local_setup_IFS
-unset _prefix_local_setup_IFS
-unset AMENT_CURRENT_PREFIX
+unset _ament_prefix_sh_source_script
+
+unset _ament_prefix_sh_AMENT_CURRENT_PREFIX
